### ISSUE TITLE
MPV 1 Review

### ISSUE THREAD

**Issue by Shaphen** [Shaphen/Badcord#2]
Hello Walker! Please review my first MVP for:

- Allow user signup, sign in, and logout
- Allowing for a demo login for the lazy at heart
- Routing restrictions
- Styling
- And whatever you feel like

-> [Here is a link to my website for your convenience](https://badcord.herokuapp.com/#/)  <-

Thanks!

**Comment by samwalker191** [comment]
- [ ] Shouldnt be able to see splash page after login, but i think this will be fixed when you finish your next mvp

the rest of my feedback is for the session forms
- [ ] try to use the same font for your forms as you did on the splash. Times New Roman isnt too pretty
- [ ] overall i think the forms need to be larger. See discords session forms.
https://discordapp.com/login
- [ ] basically, try to make your session forms look just like theirs. minus the QR code and the animation in the top left corner.
- [ ] pay close attention to details like spacing, how the inputs look, text size, etc.

**Comment by Shaphen** [comment]
Hello Walker! I refactored my code to attempt at accommodating your instructions. Unfortunately it seems i'm having a few Heroku bugs that are preventing my site from displaying. Here is a screenshot in the meantime for your reference as I try to get the live site running again.

<img width="1087" alt="Screen Shot 2020-05-02 at 8 47 43 PM" src="https://user-images.githubusercontent.com/60761331/80898253-30ddcc00-8cb6-11ea-91f1-6eef75adba2e.png">

**Comment by samwalker191** [comment]
- [ ] Button text should be same color as welcome text
- [ ] Button text should be same font as other text as well
- [ ] error messages should clear when switching between login/register forms
- [ ] when the submit button is clicked for register, it takes me to the login page when i am unsuccessful at registering.
- [ ] demo button on register tries to create a new user instead of logging in
